/**
 * 菜单相关图标定义
 * 收集了各种菜单、导航和系统功能相关的图标
 */

// 菜单和导航相关图标
export const menuNavigationIcons = {
  // Material Symbols 图标集
  materialSymbols: [
    // 菜单和导航
    'material-symbols:menu',
    'material-symbols:menu-open',
    'material-symbols:apps',
    'material-symbols:dashboard',
    'material-symbols:home',
    'material-symbols:home-outline',
    'material-symbols:arrow-back',
    'material-symbols:arrow-forward',
    'material-symbols:arrow-drop-down',
    'material-symbols:arrow-right',
    'material-symbols:expand-more',
    'material-symbols:expand-less',
    'material-symbols:chevron-left',
    'material-symbols:chevron-right',
    'material-symbols:first-page',
    'material-symbols:last-page',
    'material-symbols:list',
    'material-symbols:grid-view',
    'material-symbols:view-sidebar',
    'material-symbols:view-timeline',
    'material-symbols:menu-book',
    'material-symbols:bookmark',
    // 文件夹和组织
    'material-symbols:folder',
    'material-symbols:folder-open',
    'material-symbols:folder-special',
    'material-symbols:folder-zip',
    'material-symbols:topic',
    'material-symbols:category',
    'material-symbols:layers',
    'material-symbols:stack',
    // 系统功能
    'material-symbols:settings',
    'material-symbols:tune',
    'material-symbols:admin-panel-settings',
    'material-symbols:shield',
    'material-symbols:verified-user',
    'material-symbols:manage-accounts',
    'material-symbols:person',
    'material-symbols:group',
    'material-symbols:support',
    'material-symbols:help',
    'material-symbols:info',
    'material-symbols:warning',
    // 常用功能
    'material-symbols:search',
    'material-symbols:filter-list',
    'material-symbols:sort',
    'material-symbols:sync',
    'material-symbols:notifications',
    'material-symbols:mail',
    'material-symbols:chat',
    'material-symbols:edit',
    'material-symbols:delete',
    'material-symbols:add',
    'material-symbols:remove',
    'material-symbols:close'
  ],

  // Material Design Icons (MDI) 图标集
  mdi: [
    // 菜单和导航
    'mdi:menu',
    'mdi:menu-open',
    'mdi:home',
    'mdi:view-dashboard',
    'mdi:apps',
    'mdi:dots-grid',
    'mdi:arrow-left',
    'mdi:arrow-right',
    'mdi:chevron-down',
    'mdi:chevron-up',
    'mdi:chevron-left',
    'mdi:chevron-right',
    'mdi:page-first',
    'mdi:page-last',
    'mdi:view-list',
    'mdi:view-grid',
    'mdi:view-column',
    'mdi:view-sequential',
    'mdi:bookmark',
    'mdi:book-open',
    // 文件夹和组织
    'mdi:folder',
    'mdi:folder-open',
    'mdi:folder-outline',
    'mdi:folder-plus',
    'mdi:file-document',
    'mdi:file-tree',
    'mdi:tag',
    'mdi:tag-outline',
    // 系统功能
    'mdi:cog',
    'mdi:cog-outline',
    'mdi:tune',
    'mdi:hammer-wrench',
    'mdi:shield',
    'mdi:shield-check',
    'mdi:account',
    'mdi:account-group',
    'mdi:account-cog',
    'mdi:account-supervisor',
    'mdi:help-circle',
    'mdi:information',
    // 常用功能
    'mdi:magnify',
    'mdi:filter',
    'mdi:sort',
    'mdi:refresh',
    'mdi:bell',
    'mdi:email',
    'mdi:message',
    'mdi:pencil',
    'mdi:delete',
    'mdi:plus',
    'mdi:minus',
    'mdi:close'
  ],

  // Font Awesome 图标集
  fa6Solid: [
    // 菜单和导航
    'fa6-solid:bars',
    'fa6-solid:house',
    'fa6-solid:gauge-high',
    'fa6-solid:table-cells',
    'fa6-solid:arrow-left',
    'fa6-solid:arrow-right',
    'fa6-solid:chevron-down',
    'fa6-solid:chevron-up',
    'fa6-solid:chevron-left',
    'fa6-solid:chevron-right',
    'fa6-solid:angles-left',
    'fa6-solid:angles-right',
    'fa6-solid:list',
    'fa6-solid:grip',
    'fa6-solid:columns',
    'fa6-solid:table-list',
    'fa6-solid:bookmark',
    'fa6-solid:book-open',
    // 文件夹和组织
    'fa6-solid:folder',
    'fa6-solid:folder-open',
    'fa6-solid:folder-tree',
    'fa6-solid:folder-plus',
    'fa6-solid:file',
    'fa6-solid:file-lines',
    'fa6-solid:tag',
    'fa6-solid:tags',
    // 系统功能
    'fa6-solid:gear',
    'fa6-solid:sliders',
    'fa6-solid:screwdriver-wrench',
    'fa6-solid:shield',
    'fa6-solid:user-shield',
    'fa6-solid:users-gear',
    'fa6-solid:user',
    'fa6-solid:users',
    'fa6-solid:circle-question',
    'fa6-solid:circle-info',
    // 常用功能
    'fa6-solid:magnifying-glass',
    'fa6-solid:filter',
    'fa6-solid:arrow-up-wide-short',
    'fa6-solid:rotate',
    'fa6-solid:bell',
    'fa6-solid:envelope',
    'fa6-solid:message',
    'fa6-solid:pen-to-square',
    'fa6-solid:trash',
    'fa6-solid:plus',
    'fa6-solid:minus',
    'fa6-solid:xmark'
  ],

  // Bootstrap Icons
  bootstrap: [
    // 菜单和导航
    'bi:list',
    'bi:house-fill',
    'bi:grid-3x3-gap-fill',
    'bi:columns-gap',
    'bi:arrow-left',
    'bi:arrow-right',
    'bi:chevron-down',
    'bi:chevron-up',
    'bi:chevron-left',
    'bi:chevron-right',
    'bi:chevron-double-left',
    'bi:chevron-double-right',
    'bi:list-ul',
    'bi:grid-3x3',
    'bi:layout-sidebar',
    'bi:layout-three-columns',
    'bi:bookmark-fill',
    'bi:book',
    // 文件夹和组织
    'bi:folder-fill',
    'bi:folder2-open',
    'bi:folder-plus',
    'bi:folder-symlink',
    'bi:file-earmark',
    'bi:file-text',
    'bi:tag-fill',
    'bi:tags-fill',
    // 系统功能
    'bi:gear-fill',
    'bi:sliders',
    'bi:tools',
    'bi:shield-fill',
    'bi:shield-lock-fill',
    'bi:person-gear',
    'bi:person-fill',
    'bi:people-fill',
    'bi:question-circle-fill',
    'bi:info-circle-fill',
    // 常用功能
    'bi:search',
    'bi:funnel-fill',
    'bi:sort-down',
    'bi:arrow-repeat',
    'bi:bell-fill',
    'bi:envelope-fill',
    'bi:chat-fill',
    'bi:pencil-fill',
    'bi:trash-fill',
    'bi:plus-lg',
    'bi:dash-lg',
    'bi:x-lg'
  ]
}

// 系统管理图标
export const systemManagementIcons = {
  // Material Symbols 图标集
  materialSymbols: [
    'material-symbols:admin-panel-settings',
    'material-symbols:manage-accounts',
    'material-symbols:security',
    'material-symbols:shield',
    'material-symbols:policy',
    'material-symbols:description',
    'material-symbols:rule',
    'material-symbols:verified-user',
    'material-symbols:person-search',
    'material-symbols:supervisor-account',
    'material-symbols:badge',
    'material-symbols:account-box',
    'material-symbols:groups',
    'material-symbols:group',
    'material-symbols:settings-account-box',
    'material-symbols:monitoring',
    'material-symbols:database',
    'material-symbols:storage',
    'material-symbols:backup',
    'material-symbols:restore',
    'material-symbols:history',
    'material-symbols:update',
    'material-symbols:terminal',
    'material-symbols:developer-mode',
    'material-symbols:bug-report',
    'material-symbols:analytics'
  ],

  // Material Design Icons (MDI) 图标集
  mdi: [
    'mdi:account-cog',
    'mdi:account-key',
    'mdi:security',
    'mdi:shield-account',
    'mdi:text-box',
    'mdi:file-document',
    'mdi:ruler',
    'mdi:gavel',
    'mdi:account-search',
    'mdi:account-supervisor',
    'mdi:card-account-details',
    'mdi:account-box',
    'mdi:account-group',
    'mdi:account-multiple',
    'mdi:account-settings',
    'mdi:monitor-dashboard',
    'mdi:database',
    'mdi:server',
    'mdi:backup-restore',
    'mdi:harddisk',
    'mdi:history',
    'mdi:update',
    'mdi:console',
    'mdi:dev-to',
    'mdi:bug',
    'mdi:chart-line'
  ],

  // Font Awesome 图标集
  fa6Solid: [
    'fa6-solid:user-gear',
    'fa6-solid:user-lock',
    'fa6-solid:shield-halved',
    'fa6-solid:shield-alt',
    'fa6-solid:file-lines',
    'fa6-solid:file-contract',
    'fa6-solid:gavel',
    'fa6-solid:scale-balanced',
    'fa6-solid:user-check',
    'fa6-solid:user-group',
    'fa6-solid:id-card',
    'fa6-solid:address-card',
    'fa6-solid:users',
    'fa6-solid:user-pen',
    'fa6-solid:user-gear',
    'fa6-solid:chart-simple',
    'fa6-solid:database',
    'fa6-solid:server',
    'fa6-solid:download',
    'fa6-solid:upload',
    'fa6-solid:clock-rotate-left',
    'fa6-solid:arrows-rotate',
    'fa6-solid:terminal',
    'fa6-solid:code',
    'fa6-solid:bug',
    'fa6-solid:chart-line'
  ],

  // Bootstrap Icons
  bootstrap: [
    'bi:person-gear',
    'bi:person-lock',
    'bi:shield-lock',
    'bi:shield-check',
    'bi:file-text',
    'bi:file-earmark-text',
    'bi:rulers',
    'bi:check-square',
    'bi:person-check',
    'bi:person-plus',
    'bi:person-badge',
    'bi:person-vcard',
    'bi:people',
    'bi:person-fill-gear',
    'bi:person-fill-lock',
    'bi:speedometer2',
    'bi:database-fill',
    'bi:hdd-rack',
    'bi:cloud-download',
    'bi:cloud-upload',
    'bi:clock-history',
    'bi:arrow-clockwise',
    'bi:terminal',
    'bi:code-square',
    'bi:bug',
    'bi:graph-up'
  ]
}

// 导出所有图标集合
export const allMenuIcons = {
  'material-symbols': [
    ...menuNavigationIcons.materialSymbols,
    ...systemManagementIcons.materialSymbols
  ],
  mdi: [...menuNavigationIcons.mdi, ...systemManagementIcons.mdi],
  'fa6-solid': [...menuNavigationIcons.fa6Solid, ...systemManagementIcons.fa6Solid],
  bi: [...menuNavigationIcons.bootstrap, ...systemManagementIcons.bootstrap]
}
