/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: (typeof import('element-plus/es'))['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
    ElContainer: (typeof import('element-plus/es'))['ElContainer']
    ElDialog: (typeof import('element-plus/es'))['ElDialog']
    ElDivider: (typeof import('element-plus/es'))['ElDivider']
    ElDropdown: (typeof import('element-plus/es'))['ElDropdown']
    ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem']
    ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: (typeof import('element-plus/es'))['ElMenu']
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
    ElMenuItemGroup: (typeof import('element-plus/es'))['ElMenuItemGroup']
    ElPagination: (typeof import('element-plus/es'))['ElPagination']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    ElSelect: (typeof import('element-plus/es'))['ElSelect']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElTable: (typeof import('element-plus/es'))['ElTable']
    ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn']
    ElTag: (typeof import('element-plus/es'))['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
